spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: pocmongo
      host: localhost
      port: 27017
  output:
    ansi:
      enabled: ALWAYS

  logging:
    level:
      org:
        springframework:
          data:
            mongodb:
              core:
                MongoTemplate: DEBUG